use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'OPTIMUS L3',2,1,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G4',1,2,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'S5 MINI',2,3,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'POP 3',2,4,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'IPHONE 4S',1,5,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ZENFONE 4',2,6,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ACTIVE S',1,7,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G2 MINI',1,1,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'OPTIMUS PLUS',2,1,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G4 PRIME',1,2,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'S8',2,3,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'POP 337',2,4,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'IPHONE 8S',1,5,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ZENFONE 7',2,6,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ACTIVE S9',1,7,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G2 ',1,1,2);