use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,99887766,1,1,1);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,21728391,2,2,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,83274893,3,5,2);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,99887766,4,6,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,89324798,5,8,4);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,99665345,1,2,1);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,45612188,1,2,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,789445632,3,4,1);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,456321789,2,5,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,963654753,4,7,3);