use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'BRASIL',55);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'ARGENTINA',54);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'BOLÍVIA',591);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'CHILE',56);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'COLÔMBIA',57);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'EQUADOR',593);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'GUIANA',592);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'PARAGUAI',595);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'PERU',51);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'SURINAME',597);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'URUGUAI',598);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'VENEZUELA',58);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'AFGHANISTÃO',93);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'AUSTRÁLIA',61);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'BAHAMAS',994);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'CATAR',974);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'DINAMARCA',1767);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'ESPANHA',34);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'GRECIA',30);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'LETONIA',371);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'LIBIA',218);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'SUECIA',46);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'SUIÇA',41);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'URUGUAI',598);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'UCRANIA',380);