use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'RIO GRANDE DO SUL', 'RS',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'SANTA CATARINA', 'SC',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'PARANÁ', 'PR',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'SÃO PAULO', 'SP',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'RIO DE JANEIRO', 'RJ',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'AMAZONAS', 'AM',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'MINAS GERAIS', 'MG',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'ESPÍRITO SANTO', 'ES',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'BAHIA', 'BA',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'CEARA', 'CE',1);