use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'PORTO ALEGRE',51,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'ALEGRETE', 55,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'RIO DE JANEIRO',21,5);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'SAO PAULO',11,4);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'SALVADOR',71,9);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'BELO HORIZONTE',31,7);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'FORTALEZA',85,10);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'VITORIA',27,8);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'BAGEE',789,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'PASSO FUNDO', 788,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'TAKIO',787,5);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'MIAMI',786,4);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'LAS VEGAS',785,9);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'LISBOA',784,7);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'FLORES DA CUNHA',783,10);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'RESTIGA',782,8);