use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PARTENON',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'SÂO JOSE',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'RESTINGA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'IPANEMA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA NOVA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PETROPOLIS',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'CENTRO',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA JARDIM',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PARQUE DOS MAIA',2);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'SANTA MARIA',2);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'BOM JESUS',2);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'CRISTAL',3);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA AUGUSTA',3);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'LEOPOLDINA',3);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'MARIO QUINTANA',4);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'ALVORADA',4);