use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PARTENON',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'SÂO JOSE',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'RESTINGA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'IPANEMA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA NOVA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PETROPOLIS',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'CENTRO',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA JARDIM',1);