LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_APARELHOS.csv' 
INTO TABLE TBT_APARELHOS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_BAIRROS.csv' 
INTO TABLE TBT_BAIRROS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_CARGOS.csv' 
INTO TABLE TBT_CARGOS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_LINHAS_TELEFONICAS.csv' 
INTO TABLE TBT_LINHAS_TELEFONICAS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_CIDADES.csv' 
INTO TABLE TBT_CIDADES 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_ESTADOS.csv' 
INTO TABLE TBT_ESTADOS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_FUNCIONARIOS.csv' 
INTO TABLE TBT_FUNCIONARIOS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_GENEROS.csv' 
INTO TABLE TBT_GENEROS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_MARCAS_DE_CELULAR.csv' 
INTO TABLE TBT_MARCAS_DE_CELULAR
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_MODELOS_DE_CELULAR.csv' 
INTO TABLE TBT_MODELOS_DE_CELULAR 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_OPERADORAS_TELEFONICAS.csv' 
INTO TABLE TBT_OPERADORAS_TELEFONICAS
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_PAISES.csv' 
INTO TABLE TBT_PAISES 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_RUAS.csv' 
INTO TABLE TBT_RUAS 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE '%USERPROFILE%/Documents/git
/PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS/ProJeto Banco de Dados
/ProJeto Banco de Dados/CSV/TBT_TIPOS_DE_CHIP.csv' 
INTO TABLE TBT_TIPOS_DE_CHIP 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';
