use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'VIVO');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'CLARO');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'TIM');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'OI');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'NEXTEL');




