use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'BRASIL',55);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'ARGENTINA',54);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'BOLÍVIA',591);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'CHILE',56);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'COLÔMBIA',57);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'EQUADOR',593);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'GUIANA',592);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'PARAGUAI',595);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'PERU',51);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'SURINAME',597);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'URUGUAI',598);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'VENEZUELA',58);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'AFGHANISTÃO',93);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'AUSTRÁLIA',61);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'BAHAMAS',994);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'CATAR',974);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'DINAMARCA',1767);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'ESPANHA',34);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'GRECIA',30);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'LETONIA',371);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'LIBIA',218);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'SUECIA',46);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'SUIÇA',41);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'URUGUAI',598);
insert into TBT_PAISES(ID_PAIS,NOME_PAIS,DDI) values(null,'UCRANIA',380);

insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'RIO GRANDE DO SUL', 'RS',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'SANTA CATARINA', 'SC',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'PARANÁ', 'PR',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'SÃO PAULO', 'SP',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'RIO DE JANEIRO', 'RJ',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'AMAZONAS', 'AM',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'MINAS GERAIS', 'MG',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'ESPÍRITO SANTO', 'ES',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'BAHIA', 'BA',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'CEARA', 'CE',1);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'BERLIM', 'AF',2);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'VIENA', 'VN',2);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'SANTIAGO', 'ST',2);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'CALIFORNIA', 'CF',3);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'MADRI', 'MD',3);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'QUITO', 'QT',3);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'WASHITON', 'WS',5);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'TALIM', 'TM',5);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'CAIRO', 'CR',5);
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO,FK_ID_PAIS) values (null,'PARIS', 'PS',5);

insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'PORTO ALEGRE',51,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'ALEGRETE', 55,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'RIO DE JANEIRO',21,5);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'SAO PAULO',11,4);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'SALVADOR',71,9);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'BELO HORIZONTE',31,7);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'FORTALEZA',85,10);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'VITORIA',27,8);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'BAGEE',789,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'PASSO FUNDO', 788,1);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'TAKIO',787,5);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'MIAMI',786,4);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'LAS VEGAS',785,9);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'LISBOA',784,7);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'FLORES DA CUNHA',783,10);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD,FK_ID_ESTADO) values (null, 'RESTIGA',782,8);


insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PARTENON',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'SÂO JOSE',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'RESTINGA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'IPANEMA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA NOVA',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PETROPOLIS',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'CENTRO',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA JARDIM',1);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'PARQUE DOS MAIA',2);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'SANTA MARIA',2);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'BOM JESUS',2);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'CRISTAL',3);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'VILA AUGUSTA',3);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'LEOPOLDINA',3);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'MARIO QUINTANA',4);
insert into TBT_BAIRROS(ID_BAIRRO, NOME_BAIRRO,FK_ID_CIDADE) values (null, 'ALVORADA',4);

insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA A',1);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA B',2);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA C',3);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA D',4);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA E',5);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA F',6);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA G',7);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA H',8);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA I',1);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA J',2);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA K',3);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA A1',1);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA B2',2);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA C3',3);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA D4',4);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA E5',5);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA F6',6);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA G7',7);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA H8',8);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA I9',1);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA J10',2);
insert into TBT_RUAS(ID_RUA,NOME_RUA,FK_ID_BAIRRO) values (null, 'RUA K11',3);

insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'DIRETOR');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'GERENTE NACIONAL');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'GERENTE REGIONAL');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'GERENTE');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'COORDENADOR');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'ESPECIALISTA');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'ANALISTA');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'TÉCNICO');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'APRENDIZ');
insert into TBT_CARGOS(ID_CARGO,NOME_CARGO) values(null, 'ESTAGIÁRIO');

insert into TBT_GENEROS(ID_GENERO,NOME_GENERO) values(null,'FEMININO');
insert into TBT_GENEROS(ID_GENERO,NOME_GENERO) values(null,'MASCULINO');

insert into TBT_TIPOS_DE_CHIP(ID_TIPO_CHIP,NOME_TIPO_CHIP) values (null,'MINI-SIM');
insert into TBT_TIPOS_DE_CHIP(ID_TIPO_CHIP,NOME_TIPO_CHIP) values (null,'MICRO-SIM');
insert into TBT_TIPOS_DE_CHIP(ID_TIPO_CHIP,NOME_TIPO_CHIP) values (null,'NANO-SIM');

insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'LG');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'MOTOROLA');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'SAMSUNG');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'ALCATEL');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'APPLE');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'ASUS');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'QUANTUM');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'SONY');

insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'OPTIMUS L3',2,1,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G4',1,2,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'S5 MINI',2,3,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'POP 3',2,4,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'IPHONE 4S',1,5,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ZENFONE 4',2,6,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ACTIVE S',1,7,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G2 MINI',1,1,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'OPTIMUS PLUS',2,1,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G4 PRIME',1,2,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'S8',2,3,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'POP 337',2,4,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'IPHONE 8S',1,5,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ZENFONE 7',2,6,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ACTIVE S9',1,7,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G2 ',1,1,2);

insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'VIVO');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'CLARO');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'TIM');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'OI');
insert into TBT_OPERADORAS_TELEFONICAS(ID_OPERADORA,NOME_OPERADORA) values (null, 'NEXTEL');

insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,99887766,1,1,1);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,21728391,2,2,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,83274893,3,5,2);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,99887766,4,6,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,89324798,5,8,4);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,99665345,1,2,1);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,45612188,1,2,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,789445632,3,4,1);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,456321789,2,5,3);
insert into TBT_LINHAS_TELEFONICAS(ID_LINHA,NUMERO_TELEFONE,FK_ID_CIDADE,FK_ID_PAIS,FK_ID_OPERADORA)
values (null,963654753,4,7,3);

insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'218937129',823894733,'CLAUDIOMIRO','2000-9-11',82394738,'HELENA MARIA',8,1,4);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'1111111111',111111111,'JOÃO AUGUSTO LUCAS','1980-8-23',12891928,'LUIZA LUCAS',1,2,3);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'1283782913',328947383,'ANA SILVA','1990-1-02',21389182,'MARIA SILVA',2,1,5);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'550832369',127184923,'JULIO VIEGAS','1983-7-10',12783219,'FRANCISCA VIEGAS',10,2,7);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'789545455',789456512,'MELISSA','1983-7-10',78896523,'FRANCISCA VIEGAS',10,2,1);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'789564123',652316471,'CARLOS','1990-1-02',89656123,'MARIA EDUARDA',2,1,4);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'789653214',852613497,'VICTORIA','1983-7-10',74512369,'CRIS',3,2,4);
insert into TBT_FUNCIONARIOS(ID_FUNCIONARIO,CPF,RG,NOME_COMPLETO,DATA_NASCIMENTO,TELEFONE,NOME_DA_MAE,FK_ID_CARGO,FK_ID_GENERO,FK_ID_RUA)
values (null,'785142367',36989897,'ANDREIA','1983-7-10',97845236,'BETH',10,2,1);

insert into TBT_APARELHOS(ID_APARELHO,SENHA_APARELHO,IMEI,NUMERO_DE_SERIE,MAC_ADDRESS,FK_ID_MODELO,FK_ID_LINHA,FK_ID_FUNCIONARIO) 
values (null,'12345',1234567,987654321,'000300040009',1,1,1);
insert into TBT_APARELHOS(ID_APARELHO,SENHA_APARELHO,IMEI,NUMERO_DE_SERIE,MAC_ADDRESS,FK_ID_MODELO,FK_ID_LINHA,FK_ID_FUNCIONARIO) 
values (null,'54312',3843743,891286743,'432109871234',2,2,2);
insert into TBT_APARELHOS(ID_APARELHO,SENHA_APARELHO,IMEI,NUMERO_DE_SERIE,MAC_ADDRESS,FK_ID_MODELO,FK_ID_LINHA,FK_ID_FUNCIONARIO) 
values (null,'12839',0298347,817832928,'318237129534',3,3,3);
insert into TBT_APARELHOS(ID_APARELHO,SENHA_APARELHO,IMEI,NUMERO_DE_SERIE,MAC_ADDRESS,FK_ID_MODELO,FK_ID_LINHA,FK_ID_FUNCIONARIO) 
values (null,'28943',0857622,382289334,'484832387384',4,4,4);
insert into TBT_APARELHOS(ID_APARELHO,SENHA_APARELHO,IMEI,NUMERO_DE_SERIE,MAC_ADDRESS,FK_ID_MODELO,FK_ID_LINHA,FK_ID_FUNCIONARIO) 
values (null,'83428',2893734,324935423,'382349234953',5,5,null);