use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'OPTIMUS L3',11111111,1,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G4',22222222,2,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'S5 MINI',33333333,3,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'POP 3',44444444,4,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'IPHONE 4S',55555555,5,2);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ZENFONE 4',66666666,6,3);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'ACTIVE S',77777777,7,1);
insert into TBT_MODELOS_DE_CELULAR(ID_MODELO,NOME_MODELO,NUMERO_CHIP,FK_ID_MARCA_CELULAR,FK_ID_TIPO_CHIP) values (null, 'G2 MINI',88888888,1,2);