use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'LG');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'MOTOROLA');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'SAMSUNG');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'ALCATEL');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'APPLE');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'ASUS');
insert into TBT_MARCAS_DE_CELULAR(ID_MARCA,NOME_MARCA) values (null,'QUANTUM');