use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'RIO GRANDE DO SUL', 'RS');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'SANTA CATARINA', 'SC');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'PARANÁ', 'PR');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'SÃO PAULO', 'SP');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'RIO DE JANEIRO', 'RJ');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'AMAZONAS', 'AM');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'MINAS GERAIS', 'MG');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'ESPÍRITO SANTO', 'ES');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'BAHIA', 'BA');
insert into TBT_ESTADOS(ID_ESTADO,NOME_ESTADO,SIGLA_ESTADO) values (null,'CEARA', 'CE');