use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'PORTO ALEGRE',51);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'MOSCOU', 52);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'NEW YORK',54);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'SAO PAULO',55);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'BAHIA',56);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'BUENOS AIRES',57);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'BARCELONA',58);
insert into TBT_CIDADES(ID_CIDADE,NOME_CIDADE,DDD) values (null, 'TOKIO',59);