use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

insert into TBT_TIPOS_DE_CHIP(ID_TIPO_CHIP,NOME_TIPO_CHIP) values (null,'MINI-SIM');
insert into TBT_TIPOS_DE_CHIP(ID_TIPO_CHIP,NOME_TIPO_CHIP) values (null,'MICRO-SIM');
insert into TBT_TIPOS_DE_CHIP(ID_TIPO_CHIP,NOME_TIPO_CHIP) values (null,'NANO-SIM');