use PROJETO_CONTROLE_DE_DISPOSITIVOS_MOVEIS;

create view view_funcionarios as select


		TBT_FUNCIONARIOS.ID_FUNCIONARIO 			as 'Id do Funcionário',
		TBT_FUNCIONARIOS.NOME_COMPLETO 				as 'Nome do Funcionário',
        TBT_MODELOS_DE_CELULAR.NOME_MODELO 			as 'Modelo do Aparelho',
        TBT_MARCAS_DE_CELULAR.NOME_MARCA 			as 'Marca do Aparelho',
        TBT_LINHAS_TELEFONICAS.NUMERO_TELEFONE 		as 'Número do Telefone',
        TBT_OPERADORAS_TELEFONICAS.NOME_OPERADORA 	as 'Operadora',
        TBT_CIDADES.DDD 							as 'DDD',
        TBT_PAISES.DDI 								as 'DDI'
from TBT_FUNCIONARIOS
inner join TBT_APARELHOS				on TBT_FUNCIONARIOS.ID_FUNCIONARIO=TBT_APARELHOS.FK_ID_FUNCIONARIO
inner join TBT_MODELOS_DE_CELULAR 		on TBT_MODELOS_DE_CELULAR.ID_MODELO=TBT_APARELHOS.FK_ID_MODELO
inner join TBT_MARCAS_DE_CELULAR 		on TBT_MARCAS_DE_CELULAR.ID_MARCA=TBT_MODELOS_DE_CELULAR.FK_ID_MARCA_CELULAR	 
inner join TBT_LINHAS_TELEFONICAS 		on TBT_LINHAS_TELEFONICAS.ID_LINHA=TBT_APARELHOS.ID_APARELHO
inner join TBT_OPERADORAS_TELEFONICAS 	on TBT_OPERADORAS_TELEFONICAS.ID_OPERADORA=TBT_LINHAS_TELEFONICAS.FK_ID_OPERADORA
inner join TBT_CIDADES 					on TBT_CIDADES.ID_CIDADE=TBT_LINHAS_TELEFONICAS.FK_ID_CIDADE
inner join TBT_PAISES					on TBT_PAISES.ID_PAIS=TBT_LINHAS_TELEFONICAS.FK_ID_PAIS
order by TBT_FUNCIONARIOS.NOME_COMPLETO